export { default as Actors } from './Actors/Actors';
export { default as MovieInformation } from './MovieInformation/MovieInformation';
export { default as Movies } from './Movies/Movies';
export { default as NavBar } from './NavBar/NavBar';
export { default as Profile } from './Profile/Profile';
export { default as SideBar } from './SideBar/SideBar';
export { default as MoviesList } from './MoviesList/MoviesList';
export { default as Movie } from './Movie/Movie';
export { default as Search } from './Search/Search';
